import turtle
turtle.pensize(4)
turtle.screensize(500,500,"yellow")
turtle.color("red","blue")
turtle.begin_fill()
turtle.circle(50)
turtle.setheading(180)
turtle.penup()
turtle.forward(100)
turtle.pendown()
turtle.circle(50)
turtle.end_fill()
turtle.hideturtle()
turtle.down()
